#!/bin/bash

if [ $# -ne 4 ]; then
    echo "Usage: <path_to_file> <ants> <iterations> <method>."
    exit 1
fi

METHOD=$4

mkdir -p ebin/$METHOD

erlc -o ebin/$METHOD src/$METHOD/*.erl

erl -pz ebin/$METHOD -s main start $1 $2 $3
# erl -pz ebin -s main start problems/oliver3.tsp 2 2